In [99]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import pandas as pd
from tqdm import tqdm
from selenium.webdriver.common.keys import Keys

In [140]:
op = Options()
# op.add_argument('headless')
op.add_argument('lang=ko_KR')

driver = webdriver.Chrome('C:/Users/SSAFY/Desktop/chromedriver.exe', options=op)
driver.get('https://www.card-gorilla.com/chart/top100?term=weekly')

C:\Users\SSAFY\AppData\Local\Temp\ipykernel_19136\475597815.py:5: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('C:/Users/SSAFY/Desktop/chromedriver.exe', options=op)

In [248]:
cd_pd = pd.DataFrame()
cd_bf = pd.DataFrame()

In [250]:
for i in tqdm(range(100)):
    if i == 25:
        continue
    a = driver.find_element(By.XPATH, '//*[@id="q-app"]/section/div[1]/section/div[2]/article[1]/div/div')
    t = a.find_elements(By.TAG_NAME, 'ul')    # 100개
    
    t[i].find_element(By.CLASS_NAME, 'view_btn').click()
    temp = pd.DataFrame()
    time.sleep(1)
    temp['cd_name'] = [driver.find_element(By.XPATH, '//*[@id="q-app"]/section/div[1]/section/div/article[1]/div/div/div[2]/div[1]/strong').text]
    temp['cp'] = [driver.find_element(By.XPATH, '//*[@id="q-app"]/section/div[1]/section/div/article[1]/div/div/div[2]/div[1]/p').text]
    temp['cd_type'] = [1]
    temp['cd_img'] = [driver.find_element(By.XPATH, '//*[@id="q-app"]/section/div[1]/section/div/article[1]/div/div/div[1]/img').get_attribute("src")]
    temp['cd_perm'] = [driver.find_element(By.CLASS_NAME, 'bnf2').find_elements(By.CSS_SELECTOR, 'dl')[1].text]
    temp['cd_fee'] = [driver.find_element(By.CLASS_NAME, 'in_out').text]
    try:
        temp['cd_link'] = [driver.find_element(By.CLASS_NAME, 'app_btn').find_element(By.CSS_SELECTOR, 'a').get_attribute('href')]
    except:
        temp['cd_link'] = None
    cd_pd = pd.concat([cd_pd, temp], ignore_index=True)
    
    temp = pd.DataFrame()
    for j in driver.find_element(By.CLASS_NAME, 'lst.inner.faq_area').find_elements(By.TAG_NAME, 'dl'):
        j.find_element(By.CSS_SELECTOR, 'dt').click()
        time.sleep(.5)
        temp['cd_pd'] = [driver.find_element(By.XPATH, '//*[@id="q-app"]/section/div[1]/section/div/article[1]/div/div/div[2]/div[1]/strong').text]
        p = j.find_element(By.CSS_SELECTOR, 'dt').get_attribute('style')
        x, y = p.find('http'), p.find(';') - 2
        temp['cd_bf_img'] = [p[x:y]]
        temp['cd_bf_name'] = [j.find_element(By.CSS_SELECTOR, 'strong').text]
        temp['cd_bf_sum'] = [j.find_element(By.CSS_SELECTOR, 'i').text]
        temp['cd_bf_detail'] = [j.find_element(By.CSS_SELECTOR, 'dd').text]
        j.find_element(By.CSS_SELECTOR, 'dt').click()
        time.sleep(.5)
        cd_bf = pd.concat([cd_bf, temp], ignore_index=True)
    driver.back()
    time.sleep(1)

100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [19:35<00:00, 11.75s/it]

In [251]:
cd_pd.tail()

,cd_name,cp,cd_type,cd_img,cd_perm,cd_fee,cd_link
94,카카오뱅크 신한카드,신한카드,1,https://api.card-gorilla.com:8080/storage/card...,전월실적 없음,"국내전용 15,000원 해외겸용 15,000원",None
95,톡톡 my point카드,KB국민카드,1,https://api.card-gorilla.com:8080/storage/card...,전월실적 없음,"국내전용 12,000원 해외겸용 12,000원",None
96,알뜰교통카드,우리카드,1,https://api.card-gorilla.com:8080/storage/card...,전월실적30 만원 이상,"국내전용 13,000원 해외겸용 15,000원",None
97,the Pink,현대카드,1,https://api.card-gorilla.com:8080/storage/card...,전월실적50 만원 이상,"국내전용 150,000원 해외겸용150,000원",https://www.card-gorilla.com/card/bridge/763
98,D4@카드의정석,우리카드,1,https://api.card-gorilla.com:8080/storage/card...,전월실적30 만원 이상,"국내전용 9,000원 해외겸용 10,000원",https://www.card-gorilla.com/card/bridge/88

In [252]:
cd_bf.tail()

,cd_pd,cd_bf_img,cd_bf_name,cd_bf_sum,cd_bf_detail
645,D4@카드의정석,https://api.card-gorilla.com:8080/storage/bene...,교통,대중교통 33% 청구할인,"시내버스/지하철(후불교통기능 선택 시 제공), 택시 33% 청구할인\n- 통합 월 ..."
646,D4@카드의정석,https://api.card-gorilla.com:8080/storage/bene...,카페,"커피 4대 브랜드 통합 (스타벅스, 투썸플레이스, 커피빈, 폴바셋) 55% 청구할인","55% 청구할인\n- 매년 1월 ~ 10월 통합 월 할인한도 11,000원 (건당 ..."
647,D4@카드의정석,https://api.card-gorilla.com:8080/storage/bene...,편의점,편의점 11% 청구할인,"11%청구할인 \n- 통합 월 할인한도 3,300원 (건당 할인한도 1,100원) ..."
648,D4@카드의정석,https://api.card-gorilla.com:8080/storage/bene...,영화,"영화관 5,500원 할인","건당 할인금액 5,500원(현장결제 및 영화관 사이트)\n- 통합 월 할인한도 5,..."
649,D4@카드의정석,https://api.card-gorilla.com:8080/storage/bene...,유의사항,꼭 확인하세요!,상품출시일 및 부가서비스 변경 안내\n상품 출시일: 2018년 6월 29일\n- 카...